### PR TITLE
Turbo API: Exclude API directory from further processing.

### PR DESCRIPTION
**Pull request by Shadowfiend**
This directory has a ton of HTML files that can be very expensive to all
process for snippets and such---but we also don't need that processing. We
exclude the whole directory from processing, which improves performance for
local compilation and should also improve it for deployment to telegram.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
… Actually the slowness I was seeing may have just been an issue with the telegram-hosted `hoisted.jar` that doesn't appear in a local build. Not sure yet.

**Comment by farmdawgnation** [comment]
This looks like an easy win and what we want semantically. Should we just go ahead and ship it in?

**Comment by Shadowfiend** [comment]
Never confirmed that this was really an improvement… Or that it even did what I thought it would do… So I'm not sure we should.

**Comment by farmdawgnation** [comment]
Ah gotcha

**Comment by Shadowfiend** [comment]
(/cc @dpp) Turns out that this was a mistake on my part… `exclude-dir-from-rendering` instead of `exclude_dir_from_rendering`. Still need to double-check that this works for the containerized hoisted used in telegram now (depends on the invocation path, oddly), but got it working with standalone hoisted :tada:

**Comment by Shadowfiend** [comment]
Nope, got that wrong, but might have figured part of the issue out. hoisted/hoisted#34 tweaks some stuff that may help. Meantime I've made changes here so that the API directory should be pass-through as desired. Going to merge and see if nothing breaks, at least.

**Pull request merged**
