### PR TITLE
Replace Untyped logo with Underscore logo

### PR DESCRIPTION
**Pull request by davegurnell**
Untyped is now a partner at Underscore. This change updates our link and logo in the companies carousel.

### CODE REVIEW

**Comment by d6y** [comment]
:+1: 

Looks good to me:

lift home 2015-03-13 16-22-51

**Comment by joescii** [comment]
Got it Dave, thanks for updating us!

**Comment by joescii** [comment]
Race condition! lol.

**Comment by davegurnell** [comment]
Beautiful, guys. Thanks!

**Comment by d6y** [comment]
:-) Go team! \o/

**Pull request merged**
